Repository MIT-Emerging-Talent/ET6-foundations-group-28, pull requests merged in 2025-01, with the labels that each got.

#60 Solution of 'Decimal to Base' problem
  solutions/decimal_to_base.py
  solutions/tests/test_decimal_to_base.py
Labels: challenge

#58 Count vowels
  solutions/count_vowels.py
  solutions/tests/test_count_vowels.py
Labels: challenge

#62 Check palindrome
  solutions/is_palindrome.py
  solutions/tests/test_is_palindrome.py
Labels: challenge

#67 solution for 'Base to Decimal' challenge
  solutions/base_to_decimal.py
  solutions/tests/test_base_to_decimal.py
Labels: challenge

#79 solution for 'Base to Base' challenge
  solutions/base_to_base.py
  solutions/tests/test_base_to_base.py
Labels: challenge

#83 Find the maximum challenge
  solutions/find_max.py
  solutions/tests/test_find_max.py
Labels: challenge

#82 Convert temperature challenge
  solutions/celsius_to_fahrenheit.py
  solutions/tests/test_celsius_to_fahrenheit.py
Labels: challenge

#74 Check even or odd challenge
  solutions/is_even.py
  solutions/tests/test_is_even.py
Labels: challenge

#64 Solution for Find Smallest Challenge
  solutions/find_smallest.py
  solutions/tests/test_find_smallest.py
Labels: challenge

#78 Add two number challenge
  solutions/add_2_numbers.py
  solutions/tests/test_add_2_numbers.py
Labels: challenge

#86 Added between-two-sets solution and tests
  solutions/between_two_sets.py
  solutions/tests/test_between_two_sets.py
Labels: challenge

#92 Readme update
  README.md
Labels: documentation

#85 String length
  solutions/string_length.py
  solutions/tests/test_string_length.py
Labels: challenge

#96 Meeting minutes 05
  notes/meeting_minutes/01_meeting_minutes.md
  notes/meeting_minutes/05_meeting_minutes.md
Labels: documentation

#100 Update learning_goals.md
  collaboration/learning_goals.md
Labels: documentation

#102 Update communication.md
  collaboration/communication.md
Labels: documentation

#98 Add multiplication table challenge solution
  solutions/multiplication_table.py
  solutions/tests/test_multiplication_table.py
Labels: challenge

#80 Find kth largest in a list
  solutions/kth_largest.py
  solutions/tests/test_kth_largest.py
Labels: challenge

#105 Update the last meeting minutes
  notes/meeting_minutes/06_meeting_minutes.md
Labels: documentation

#112 Add Final Documentation Update
  .vscode/settings.json
  README.md
  collaboration/README.md
  collaboration/constraints.md
  collaboration/retrospective.md
Labels: documentation

#114 Add module headers for some solutions and tests files
  solutions/add_2_numbers.py
  solutions/between_two_sets.py
  solutions/count_vowels.py
  solutions/find_prime.py
  solutions/find_smallest.py
  solutions/is_even.py
  solutions/is_palindrome.py
  solutions/kth_largest.py
  solutions/sum_numbers.py
  solutions/tests/test_add_2_numbers.py
  solutions/tests/test_between_two_sets.py
  solutions/tests/test_count_vowels.py
  solutions/tests/test_find_prime.py
  solutions/tests/test_find_smallest.py
  solutions/tests/test_is_even.py
  solutions/tests/test_is_palindrome.py
  solutions/tests/test_kth_largest.py
  solutions/tests/test_sum_numbers.py
Labels: enhancement
